# Generated by Django 4.1.1 on 2022-09-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('CPF', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birthDate', models.DateField()),
                ('profession', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('telephone', models.IntegerField()),
            ],
        ),
    ]
