# Generated by Django 4.1.1 on 2022-09-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('synopsis', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('isbn', models.IntegerField()),
            ],
        ),
    ]
